res/urls.py
from django.urls import path
from . import views

app_name="res"

urlpatterns = [
    path('',views.res),
    #localhost/res/res => booking.html
    path('booking/',views.booking),
    path('lightbox/',views.box)
]

review/urls.py
from django.urls import path
from . import views

app_name="REVIEW"
urlpatterns = [
    path('',views.reviewindex,name="reviewindex"),
    # path('create/',views.create)
]

trvl_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('member/', include('member.urls')),
    path('review/',include('review.urls')),
    path('trip/',include('trip.urls')),
    path('res/',include('res.urls')),
    path('hotel/',include('hotel.urls')),
]

review/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from member import models as m1


class Hotel(models.Model):
    id_hotel = models.IntegerField(primary_key=True)
    country_id = models.CharField(max_length=20, blank=True, null=True)
    reigien_id = models.CharField(max_length=45, blank=True, null=True)
    title = models.CharField(max_length=45, blank=True, null=True)
    h_price = models.CharField(max_length=45, blank=True, null=True)
    type = models.CharField(max_length=45, blank=True, null=True)
    addr = models.CharField(max_length=45, blank=True, null=True)
    imgsrc = models.CharField(max_length=200, blank=True, null=True)
    offical_url = models.CharField(max_length=200, blank=True, null=True)
    style = models.CharField(max_length=200, blank=True, null=True)
    style1 = models.CharField(max_length=200, blank=True, null=True)
    h_price1 = models.CharField(max_length=200, blank=True, null=True)
    tel = models.CharField(max_length=45, blank=True, null=True)
    time = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'hotel'


class Restaurant(models.Model):
    resid = models.IntegerField(db_column='Resid', primary_key=True)  # Field name made lowercase.
    country_id = models.CharField(max_length=200, blank=True, null=True)
    region_id = models.CharField(max_length=200, blank=True, null=True)
    type = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    time = models.CharField(max_length=500, blank=True, null=True)
    tel = models.CharField(max_length=200, blank=True, null=True)
    remainingseats = models.IntegerField(db_column='RemainingSeats', blank=True, null=True)  # Field name made lowercase.
    addr = models.CharField(max_length=200, blank=True, null=True)
    imgsrc = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'restaurant'


class Attraction(models.Model):
    idattraction = models.IntegerField(db_column='idAttraction', primary_key=True)  # Field name made lowercase.
    title = models.CharField(max_length=100, blank=True, null=True)
    time = models.CharField(max_length=500, blank=True, null=True)
    addr = models.CharField(max_length=1000, blank=True, null=True)
    imgsrc = models.CharField(max_length=1000, blank=True, null=True)
    officailurl = models.CharField(max_length=1000, blank=True, null=True)
    country_id = models.IntegerField(blank=True, null=True)
    region_id = models.IntegerField(blank=True, null=True)
    type = models.CharField(max_length=1000, blank=True, null=True)
    tel = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'attraction'


class Review(models.Model):
    memberid = models.ForeignKey(m1.Member, models.DO_NOTHING, db_column='MemberID')  # Field name made lowercase.
    typeplace = models.CharField(db_column='TypePlace', max_length=45, blank=True, null=True)  # Field name made lowercase.
    placeid = models.CharField(db_column='PlaceID', max_length=45, blank=True, null=True)  # Field name made lowercase.
    rating = models.CharField(db_column='Rating', max_length=45, blank=True, null=True)  # Field name made lowercase.
    datereview = models.CharField(db_column='DateReview', max_length=45, blank=True, null=True)  # Field name made lowercase.
    contentofreview = models.CharField(db_column='ContentofReview', max_length=5000, blank=True, null=True)  # Field name made lowercase.
    idreview = models.IntegerField(db_column='idReview', primary_key=True)  # Field name made lowercase.
    hastable = models.CharField(db_column='HasTable', max_length=500, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'review'

review/views.py
from django.shortcuts import render,redirect
from django.db import connection
from .models import Review as rw
from .models import Attraction as at
from .models import Hotel as ht
from .models import Restaurant as rest
from member import models as m1
from django.db.models import Avg,Count
import random
# Create your views here.
def reviewindex(request):
    TupleOfReview = []

    #Check for login
    isFooterShow=False
    if 'user' in request.session:
        useris = request.session['user']
        isLogin = True
    else:
        return redirect('../member/')

    #Save data to session
    if request.method=="GET":
        pid = request.GET['placeide']
        request.session['placeide'] = pid
        request.session.modified = True

    if request.method=="POST":
        print('in post')
        print(request.session['placeide'])
        TextArea = request.POST['TextArea']
        SeperateTextArea = TextArea.split("#")
        TrueTextArea = SeperateTextArea[0]
        HastagText = ",".join(SeperateTextArea[1:])
        # Get random ID
        ReviewID = random.randint(208398, 299999)
        DateOfReview = request.POST['HReviewTime']
        PlaceID = request.session['placeide']
        MemberID = m1.Member.objects.get(idmember=useris[0])
        StarCounts = request.POST['HStarCount']
        rw.objects.create(contentofreview = TrueTextArea,memberid = MemberID,datereview = DateOfReview,idreview = ReviewID,placeid = PlaceID,typeplace = 'Shopping',rating = StarCounts,hastable = HastagText)
        print('post func')
        

        if 'placeide' in request.session:
            placeide = request.session['placeide']
            return redirect('/review/?placeide={}'.format(placeide))
        else:
            return redirect('/trip')

    #Judge Where to read database
    if pid.startswith('3'):
        CorrectPlace = at.objects.filter(idattraction = pid).get()
        print(CorrectPlace)
    elif pid.startswith('5'):
        CorrectPlace = rest.objects.filter(resid = pid).get()
    elif pid.startswith('6'):
        CorrectPlace = ht.objects.filter(id_hotel = pid).get()
    else:
        print("False")

    # Get the MainPlace by filter & order review by time
    MainPlace = rw.objects.filter(placeid = pid)
    reviews = rw.objects.filter(placeid = pid).order_by('-datereview')

    # This is for filter out the place name, and get the range for stars
    HI3 = MainPlace.aggregate(Avg('rating'))
    TOTALREVIEWC = MainPlace.aggregate(Count('contentofreview'))
    if HI3['rating__avg'] is not None:
        AVGGSTARR = range(round(HI3['rating__avg']))
        AVGBSTARR = range(5-round(HI3['rating__avg']))
    else:
        AVGGSTARR = range(0)
        AVGBSTARR = range(0,5)
    ShowAllHasTag = MainPlace.values('hastable')

    #Calculate Stars to show on the popover box
    StarsProgress = StarsProgressBar(MainPlace,TOTALREVIEWC)

    #Show Hastable
    HasTList = []
    for showHastab in ShowAllHasTag:
        if showHastab['hastable']!=None:
            if showHastab['hastable'] not in HasTList:
                HasTList = HasTList + showHastab['hastable'].split(',')
            else:
                pass
        else:
            pass
    HasTList = HasTList[1:]
    HasTList=set(HasTList)

    # Present Data onto detail box
    CorrectPlaceName = CorrectPlace.title
    CorrectPlaceType = CorrectPlace.type
    CorrectPlacePic = CorrectPlace.imgsrc
    if CorrectPlace.tel is None:
        CorrectPlacePhone = "none"
    else:
        CorrectPlacePhone = CorrectPlace.tel
    CorrectPlaceAddr = CorrectPlace.addr
    CorrectPlaceTime = CorrectPlace.time
    if CorrectPlace.time is '':
        CorrectPlaceTime = "Open 24 hours"
    else:
        CorrectPlaceTime = CorrectPlace.time

    # Using for loop to seperate the items we need.
    for memberreview in reviews:

        # memberreview.memberid will return Member object
        AllName = memberreview.memberid.membername.split('/')
        RealName = AllName[0] + " " + AllName[1]
        RealContent = memberreview.contentofreview.split('\r\n')
        RealGStar = range(int(memberreview.rating))
        RealBStar = range(5-int(memberreview.rating))
        # print(RealBStar)
        TupleOfReview.append((RealContent,RealGStar,RealName,memberreview.datereview,RealBStar))

    #Post

    # if request.method=="POST":
    #     print('in post')
    #     TextArea = request.POST['TextArea']
    #     SeperateTextArea = TextArea.split("#")
    #     TrueTextArea = SeperateTextArea[0]
    #     HastagText = ",".join(SeperateTextArea[1:])
    #     # Get random ID
    #     ReviewID = random.randint(200000, 299999)
    #     DateOfReview = request.POST['HReviewTime']
    #     PlaceID = '1'
    #     MemberID = m1.Member.objects.get(idmember=useris[0])
    #     StarCounts = request.POST['HStarCount']
    #     rw.objects.create(contentofreview = TrueTextArea,memberid = MemberID,datereview = DateOfReview,idreview = ReviewID,placeid = PlaceID,typeplace = 'Happy',rating = StarCounts,hastable = HastagText)
    #     print('post func')

    #     if 'placeide' in request.session:
    #         placeide = request.session['placeide']
    #         return redirect('/review/?placeide={}'.format(placeide))
    #     else:
    #         return redirect('/trip')

    print('after post func')
    return render(request,'review/ReviewHome.html',locals())

def StarsProgressBar(M,T):
    #This is a Table of stars
    StarTable = {}
    #Get the total Count of review
    ThisisProgressBar = T['contentofreview__count']
    # FStar = M.filter(rating=5).aggregate(Count('rating'))
    if ThisisProgressBar != 0:
        for x in range(1,6):
            FStar = M.filter(rating=x).aggregate(Count('rating'))
            StarTable[str(x)+'Star'] = str(round((FStar['rating__count']/ThisisProgressBar)*100))+"%"
    else:
        for x in range(1,6):
            StarTable[str(x)+'Star'] = str(0)+"%"
    return StarTable

review/templates/review/AddingtoNewTrip.html
<select class="" name="">
  <option value="">2018/05/01</option>
  <option value="">2</option>
</select>
<!-- <button type="button" class="btn btn-info"><i class="fas fa-thumbs-up">  Add to my trip!</i></button> -->
<button type="button" class="btn btn-primary" style="border-color:#484848;background-color:#484848;width:45px;height:35px"><i class="fas fa-bookmark" style="font-size:21px"></i></button>
<select class="" name="">

</select>

review/templates/review/AvgStarShow.html
<div style="height:100%;width:100%;">

  {% for z in AVGGSTARR %}
  <i class="fas fa-star StyleofAvgStars" style="color:#ffb400"></i>
  {% endfor %}
  {% for z in AVGBSTARR %}
  <i class="fas fa-star StyleofAvgStars"></i>
  {% endfor %}
  <span id='popoverStuff' class ="StyleofAvgReview" data-trigger='hover' data-toggle='popover' data-placement='left'>{{TOTALREVIEWC.contentofreview__count}} reviews</span><br>
</div>
<div class="hide" id="popover-content">
  <table>
    <tr>
      <td>5 Stars</td>
      <td><div class="progress" style="height: 20px;width:100px;margin:3px;">
        <div class="progress-bar" role="progressbar" style="width:{{StarsProgress.5Star}};display:inline;" aria-valuenow="30" aria-valuemin="0" aria-valuemax="100"></div>
      </div></td>
    </tr>
    <tr>
      <td>4 Stars</td>
      <td><div class="progress" style="height: 20px;width:100px;margin:3px;">
        <div class="progress-bar" role="progressbar" style="width:{{StarsProgress.4Star}};display:inline;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div></td>
    </tr>
    <tr>
      <td>3 Stars</td>
      <td><div class="progress" style="height: 20px;width:100px;margin:3px;">
        <div class="progress-bar" role="progressbar" style="width:{{StarsProgress.3Star}};display:inline;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div></td>
    </tr>
    <tr>
      <td>2 Stars</td>
      <td><div class="progress" style="height: 20px;width:100px;margin:3px;">
        <div class="progress-bar" role="progressbar" style="width:{{StarsProgress.2Star}};display:inline;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div></td>
    </tr>
    <tr>
      <td>1 Stars</td>
      <td><div class="progress" style="height: 20px;width:100px;margin:3px;">
        <div class="progress-bar" role="progressbar" style="width:{{StarsProgress.1Star}};display:inline;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
      </div></td>
    </tr>
  </table>
  <!-- <label class="PopoverTotoalreviews">Total views</label> -->

</div>

review/templates/review/DetailInfo.html
{% load static %}
  <i class="fas fa-map-marker Styleofsmallicon"></i>
  <span class='Styleofsmallparagraph'>{{CorrectPlaceAddr}}</span><br>

  <i class="fas fa-phone-square Styleofsmallicon"></i>
  <span class='Styleofsmallparagraph'>{{CorrectPlacePhone}}</span><br>
  <i class="far fa-calendar-alt Styleofsmallicon"></i>
  <span class="Styleofsmallparagraph">{{CorrectPlaceTime}}</span><br>
  
  {% for x in HasTList%}
  <span><i class="fas fa-hashtag btn btn-secondary StyleofHashTags">{{x}}</i></span>
  {% endfor %}

review/templates/review/HashTagList.html
{% load static %}
{% for x in HasTList%}
<span><i class="fas fa-hashtag btn btn-secondary StyleofHashTags">{{x}}</i></span>
{% endfor %}

review/templates/review/OtherPplRate.html
{% load static %}
<div class="OtherRateBlock">
  <div class="OtherRateBlockStyle row">
    <!-- Other Ppl's ID place -->
    {% for OtherReviewDetail in TupleOfReview %}
    <div class="col-3" style="padding:5px 5px;margin-bottom:15px">
      <div class="OthersID">
        <!-- OtherUserID -->
        <span style="margin:0px">{{OtherReviewDetail.2}}</span><br>
        <!-- Time of rating -->
        <span class="TimeOfReview">{{OtherReviewDetail.3}}</span><br>
        <!-- OtherUserRating -->
        {% for x in OtherReviewDetail.1%}
        <i class="fas fa-star OthersStar" style="color:#ffb400"></i>
        {% endfor %}
        {% for x in OtherReviewDetail.4%}
        <i class="fas fa-star OthersStar"></i>
        {% endfor %}
      </div>
    </div>
    <div class="col-9" style="padding:5px 5px;margin-bottom:15px;background-color:#EEEEEE;border-radius:10px">
      <div class="OthersReview">
        {% for x in OtherReviewDetail.0 %}
        <p>{{x}}</p>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>

review/templates/review/ReviewHome.html
{% extends 'master.html' %}
{% load static %}
<!-- Load my own -->
{% block style_part %}
<link rel="stylesheet" href="{% static 'styles/review.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.1/jquery.fancybox.min.css" />
<style media="screen">
.MainPicSizeAdjust{
  background-image:url({{CorrectPlacePic}});
  width: 100%;
  height:500px;
  /* max-height:750px; */
  background-position:center;
  background-repeat:no-repeat;
  background-size:cover;
}
</style>
{% endblock %}
<!-- Show my content -->
{% block main_content %}
<div class="row ReviewHomeMainPicSize">
    {% include 'review/ReviewPic.html' %}
  <div class = "col-4 DetailInfo_TripCheck">
    <div class="theDetailTitle">{{CorrectPlaceName}}</div>
    <span class='theDetailSmallTitle'>{{CorrectPlaceType}}</span>
    <div class="row">
      <!-- First row is for important information -->
      <div class="col-12">
        {% include 'review/AvgStarShow.html' %}
      </div>
      <div class="col-12">
        {% include 'review/DetailInfo.html' %}
      </div>
      <div class="col-12" style="margin-top: 20px">
        <iframe src="https://www.facebook.com/plugins/share_button.php?href=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&layout=button&size=small&mobile_iframe=true&width=53&height=20&appId" width="53" height="20" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true" allow="encrypted-media"></iframe>
      </div>
    </div>
  </div>
</div>
<!-- This is the part for user to rate and comment. -->
<div class="row ReviewHomeMainPicSize">
  <div class="col-3 TheUserRate">
    {% include 'review/TheUserRate.html'%}
  </div>
</div>
<!-- This is the part for other ppl's rate and comment. -->
<div class="ReviewHomeMainPicSize">
  {% include 'review/OtherPplRate.html' %}
</div>
{% endblock %}
<!-- Load my JS -->
{% block script_part%}
<script src="{%static 'scripts/review.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.1/jquery.fancybox.min.js"></script>
{% endblock %}

review/templates/review/ReviewPic.html
<!-- Slideshow container -->
{% load static %}
<div class="slideshow-container col-8 MainPicSizeAdjust">
  <!-- Full-width images with number and caption text -->
  <!-- <div class="mySlides">
    <img src={{CorrectPlacePic}} style="width:100%" class= "haha">
  </div> -->

</div>

review/templates/review/TheUserRate.html
{% load static %}
<i class="fas fa-star TheUserStars" id="1"></i>
<i class="fas fa-star TheUserStars" id="2"></i>
<i class="fas fa-star TheUserStars" id="3"></i>
<i class="fas fa-star TheUserStars" id="4"></i>
<i class="fas fa-star TheUserStars" id="5"></i>
<a data-fancybox data-animation-duration="700" data-src="#animatedModal" href="javascript:;" class="btn btn-primary" id="IcountStars"><i class="fas fa-comment-alt" style="font-size:21px;"></i></a>

<div style="display: none;width: 37%;height: 60%;" id="animatedModal" class="animated-modal">
  <div class="StarDiv">
    <i class="fas fa-star TheUserStars TheLastStar" id="6"></i>
    <i class="fas fa-star TheUserStars TheLastStar" id="7"></i>
    <i class="fas fa-star TheUserStars TheLastStar" id="8"></i>
    <i class="fas fa-star TheUserStars TheLastStar" id="9"></i>
    <i class="fas fa-star TheUserStars TheLastStar" id="10"></i>
  </div>
  <form class="" action="{% url 'REVIEW:reviewindex' %}" method="post">
    {% csrf_token %}
    <textarea name="TextArea" rows="8" cols="80" maxlength="500" id="ImHere"></textarea>
    <input type="hidden" id="HiddenStarCount" name="HStarCount" value="">
    <input type="hidden" id="HiddenReviewTime" name="HReviewTime" value="">
    <button type="submit" class="btn btn-info" id="FINALSTARCOUNT"><i class="fas fa-thumbs-up">Review</i></button>
  </form>
</div>