res/urls.py
from django.urls import path
from . import views

app_name="res"

urlpatterns = [
    path('',views.res),
    #localhost/res/res => booking.html
    path('booking/',views.booking),
    path('lightbox/',views.box)
]

trip/urls.py
from django.urls import path
from . import views

app_name="trip"
urlpatterns=[
    path('', views.trip,name='trip'),
    path('ajax/Wchange/',views.Wchange,name='WChange'),
    path('trippost/', views.trippost,name='trippost'),
]

trvl_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('member/', include('member.urls')),
    path('review/',include('review.urls')),
    path('trip/',include('trip.urls')),
    path('res/',include('res.urls')),
    path('hotel/',include('hotel.urls')),
]

trip/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Attraction(models.Model):
    idattraction = models.IntegerField(db_column='idAttraction', primary_key=True)  # Field name made lowercase.
    title = models.CharField(max_length=100, blank=True, null=True)
    time = models.CharField(max_length=500, blank=True, null=True)
    addr = models.CharField(max_length=1000, blank=True, null=True)
    imgsrc = models.CharField(max_length=1000, blank=True, null=True)
    officailurl = models.CharField(max_length=1000, blank=True, null=True)
    country_id = models.IntegerField(blank=True, null=True)
    region_id = models.IntegerField(blank=True, null=True)
    type = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'attraction'


class Hotel(models.Model):
    id_hotel = models.IntegerField(primary_key=True)
    country_id = models.CharField(max_length=20, blank=True, null=True)
    reigien_id = models.CharField(max_length=45, blank=True, null=True)
    title = models.CharField(max_length=45, blank=True, null=True)
    h_price = models.CharField(max_length=45, blank=True, null=True)
    type = models.CharField(max_length=45, blank=True, null=True)
    addr = models.CharField(max_length=45, blank=True, null=True)
    imgsrc = models.CharField(max_length=200, blank=True, null=True)
    offical_url = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'hotel'


class Restaurant(models.Model):
    resid = models.IntegerField(db_column='Resid', primary_key=True)  # Field name made lowercase.
    country_id = models.CharField(max_length=200, blank=True, null=True)
    region_id = models.CharField(max_length=200, blank=True, null=True)
    type = models.CharField(max_length=200, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    time = models.CharField(max_length=500, blank=True, null=True)
    tel = models.CharField(max_length=200, blank=True, null=True)
    remainingseats = models.IntegerField(db_column='RemainingSeats', blank=True, null=True)  # Field name made lowercase.
    addr = models.CharField(max_length=200, blank=True, null=True)
    imgsrc = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'restaurant'

trip/views.py
from django.shortcuts import render,redirect
# from django.core.files.storage import fileSystemStorage
# from . import modelscreate
# We need this in order to return Json format
from django.http import JsonResponse,HttpResponse
from member import models as m1
from .models import Restaurant as rest
from member import member_models as MB
import random
from .models import Hotel as hotel
from .models import Attraction as attr
from review.models import Review as rw
from django.db.models import Avg

# def trip(request):
    # 	if request.method == 'POST':
	# 	""=request.POST.get('')
	# return render(request,'trip/trip.html',locals())


def trip(request):
    print('======================================================')
    context = "the trip page"
    tripid_fromsession = None
    triptotalday = None
    triptotalpanel = None

    useris = None

    if 'user' in request.session:
        useris = request.session['user']
        print("GET {}".format(useris))
        isLogin = True

    else:
        print("NO GET")

    print('post part')

    if request.method == "POST":  
        print('START POST')
        
        if_trip_exist = MB.Member()
        trip_day_res = if_trip_exist.select_one('SELECT count(B.idday) FROM travel.itinerary as A, travel.itinerary_day as B where A.TripID = B.TripID and A.idMember = %s;', useris)
        trip_res = if_trip_exist.select_one('SELECT count(TripID) FROM travel.itinerary where idMember = %s;', useris)

        if trip_res is not None :
            if trip_res[0] != 0 and trip_day_res[0] == 0:
                print('start dalete')
                if_trip_exist.excute_sql('delete from travel.itinerary where idMember = %s;', useris)
            else:
                # print('pass' + trip_res[0] + "/" + trip_day_res[0])
                print('no need dalete')
        else:
            print('is all good')

        tripid = random.randint(700000, 799999)   
        userid = request.session['user']   
        tripname = request.POST["tripname"]
        miantrip_country = request.POST["miantrip_country"]
        miantrip_region = request.POST["miantrip_region"]
        departyear = request.POST["departyear"]
        departmonth = request.POST["departmonth"]
        departday = request.POST["departday"]
        totaltripdate = departyear+"/"+departmonth+"/"+departday
        tripday = request.POST["tripday"]
        Travelers = request.POST["Travelers"]
        Travelpath = request.POST["Travelpath"]
        check = request.POST.getlist("Style")
        Stylelist = '/'.join(check)
        trip_data = MB.Member()
        trip_data.excute_sql("INSERT INTO travel.itinerary (TripID, idMember, TripName, Day, Arrival, Travelers, Paced, Style, idCountry, idRegion) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s);", tripid, userid, tripname, tripday, totaltripdate, Travelers, Travelpath, Stylelist, miantrip_country, miantrip_region)

        request.session['tripid'] = tripid
        request.session.modified = True

        request.session['tpday'] = tripday
        request.session.modified = True

        tripid_fromsession = request.session['tripid']
        triptotalday = range(2, int(request.session['tpday'])+1)
        triptotalpanel = range(1, int(request.session['tpday'])+1)

        print(tripname)
        print('')
        print(miantrip_country)
        print('')
        print(miantrip_region)
        print('')
        print(departyear+"/"+departmonth+"/"+departday)
        print('')
        print(tripday)
        print('')
        print(Travelers)
        print('')
        print(Travelpath)
        print('')
        print(Stylelist)
        print('')

    print('end part')

    if 'tripid' in request.session:
         tripid_fromsession = request.session['tripid']
    else:
        print('NO tripid')
    
    if 'tpday' in request.session:
         triptotalday = range(2, int(request.session['tpday'])+1) 
         triptotalpanel = range(1, int(request.session['tpday'])+1) 
    else:
        print('NO tpday')
        
    return render(request,'trip/trip.html',locals())


def trippost(request):
    # request.session.clear()
    # isFooterShow = True
    # print("XDDDD")
    if request.method == "POST":
        if 'tpday' in request.session:
            totalday = int(request.session['tpday'])+1
            print(totalday)
            for days in range(1,totalday):
                print('day{}'.format(days))
                attrname = 'i_daysp'+str(days)
                hotelname = 'i_daysh'+str(days)
                resname = 'i_daysr'+str(days)
                get_attr= request.POST[attrname] 
                get_hot= request.POST[hotelname]
                get_res= request.POST[resname]
                tripid = request.session['tripid']

                if get_attr is None:
                    get_attr = ''
                else:
                    get_attr= request.POST[attrname][:-1]

                if get_hot is None:
                    get_hot = ''
                else:
                    get_hot= request.POST[hotelname][:-1]

                if get_res is None:
                    get_res = ''
                else:
                    get_res= request.POST[resname][:-1]

                print(tripid)
                print(get_attr)
                print(get_hot)
                print(get_res)
                print('')
                trip_data = MB.Member()
                trip_data.excute_sql("insert into itinerary_day values(%s, %s, %s, %s, %s);", days, get_hot, get_res, tripid, get_attr)

            return redirect('../../res/booking')
        else:
            pass






    return render(request, 'trip/trip.html', locals())


#Create a function for Ajax to call later
def Wchange(request):
    print("HI")
    #Define a variable for ajax to into.
    CurrentFilter = request.GET.get('CurrentFilter',None).strip()
    CheckForSelect = request.GET.get('CheckForSelect',None).strip()
    #Create Empty list for input
    ImList = []
    #Get Everything from database
    if CheckForSelect == "Attraction":
        Info = attr.objects.filter(type=CurrentFilter)
    elif CheckForSelect == "Restaurant":
        Info = rest.objects.filter(type=CurrentFilter)
    elif CheckForSelect == "Hotel":
        Info = hotel.objects.filter(type=CurrentFilter)
    else:
        if CheckForSelect == "Attraction":
            Info = attr.objects.all()
        elif CheckForSelect == "Restaurant":
            Info = rest.objects.all()
        elif CheckForSelect == "Hotel":
            Info = hotel.objects.all()
    #Loop through the Query Objects
    for x in Info:
        #Create a new Dictionary
        ImDict = {}
        Name = x.title
        ImDict['Name'] = Name
        Img = x.imgsrc
        ImDict['Img'] = Img
        if CheckForSelect == "Attraction":
            Idlala = x.idattraction
        elif CheckForSelect == "Restaurant":
            Idlala = x.resid
        elif CheckForSelect == "Hotel":
            Idlala = x.id_hotel
        ImDict['Id'] = Idlala
        print(ImDict['Id'])

        #Get the average stars of different places.
        RewStarCount = rw.objects.filter(placeid=Idlala)
        print(RewStarCount)
        HI3 = RewStarCount.aggregate(Avg('rating'))
        if HI3['rating__avg'] is not None:
            ImDict['GetRating'] = round(HI3['rating__avg'])
        else:
            ImDict['GetRating'] = HI3['rating__avg'] = 0
        print("-----")
        #Get Session for how many days
        ImDict['GetTpday'] = request.session['tpday']
        # print(ImDict['GetTpday'])
        # print(type(ImDict['GetTpday']))

        #Pass in the data to list
        ImList.append(ImDict)

    return JsonResponse(ImList,safe=False)

trip/templates/trip/create.html
<!-- 行程前置表單 -->
<!DOCTYPE html>
<html lang="zh-Hant-TW">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css"></link>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <style>
        td{padding:0em 0em 0.5em 1.2em}
        fieldset{border:0em}
    </style>
    <script>
        $(function () {
            $('input.dates').daterangepicker({
    "autoApply": true,
    "maxSpan": {
        "days": 7},
    "locale": {
        "format": "MM/DD/YYYY",
        "separator": " - ",
        "applyLabel": "Apply",
        "cancelLabel": "Cancel",
        "fromLabel": "From",
        "toLabel": "To",
        "customRangeLabel": "Custom",
        "weekLabel": "W",
        "daysOfWeek": [
            "S",
            "M",
            "T",
            "W",
            "T",
            "F",
            "S"
        ],
        "monthNames": [
            "January",
            "February",
            "March",
            "April",
            "May",
            "June",
            "July",
            "August",
            "September",
            "October",
            "November",
            "December"
        ],
        "firstDay": 1
    },
    "startDate": "05/18/2018",
    "endDate": "05/24/2018"
    },
    function(start, end, label) {
    console.log('New date range selected: ' + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD') + ' (predefined range: ' + label + ')');
    })});
    </script>

</head>
<body>
    <form action="#" method="POST" enctype="multipart/form-data" style="padding-left: 20px; font-family: 'Roboto', sans-serif;color:#010101c7;font-weight:600;">
        <fieldset>
            <table>
               <tr> 
                <td><label for="tripname"><i class="fas fa-bookmark"></i></label></td>
                <td><input type="text" name="tripname" placeholder="為這趟旅行命名"></td>
                </tr>
                <tr> 
                    <td><label for="location"><i class="fas fa-map-marker-alt"></i></label></td>
                    <td><select name="country" form="country" id="country">
                    <option value="" disable selected>國家</option>
                    <option value="tw">台灣</option>
                    <option value="us">美國</option>
                    <option value="jp">日本</option>
                  </select>
                <select name="city" form="city" id="city">
                    <option value="" disable selected>城市</option>
                        <option value="us"></option>
                        <option value="jp"></option>
                </select></td>
            </tr>
            <tr>
                    <td><label for="daterange"><i class="fas fa-calendar-alt"></i></label></td>
                    <td><input class="dates" type="text" name="daterange"></td>
            </tr>
            <tr>
                <td><label for="Travelers"><i class="fas fa-user-friends"></i></label></td>
                <td><input type="number" id="Travelers" min="1" max="12" placeholder="人" size="15"></td>
            </tr>
            <tr>
                <td><label for="Paced"><i class="fas fa-shoe-prints" data-fa-transform="rotate-90"></i></label></td>
                <td>愜意<input type="range" id="Paced" value="2",min="1" max="4" step="1">充實</td>
            </tr>
                    <tr>
                        <td><label for="Style"><i class="fas fa-map-signs"></i></label></td>
                        <td><input type="checkbox" id="Style" value="kid">家庭 <input type="checkbox" id="Style" value="cul">文化 <input type="checkbox" id="Style" value="foo">美食 
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type="checkbox" id="Style" value="rom">浪漫 
                        <input type="checkbox" id="Style" value="nat">自然 <input type="checkbox" id="Style" value="sho">購物 </td>
                    </tr>
                    <tr>
                            <td></td>
                            <td style="padding-top: 0.8em">
                                    <input type="reset" value="Restart">
                                    <input type="submit" value="Let's GO"></td>
                        </tr>
                </table>
        </fieldset>
    </form>
</body>

</html>

trip/templates/trip/day.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="../../datep/css/bootstrap.css" rel="stylesheet">
    <link href="../../datep/css/bootstrap-datepaginator.css" rel="stylesheet">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="/resources/demos/style.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <style>
        body {font-family: 'Roboto', sans-serif; color: gray; padding-top: 10px;}
details {position: relative;}
details summary::-webkit-details-marker {
  display: none;
}
details summary::before {
  content: "";
  position: absolute;
  left: 0;
  background: url("data:image/svg+xml;base64,PHN2ZyBoZWlnaHQ9IjM0IiB2aWV3Qm94PSIwIDAgMjQgMjQiIHdpZHRoPSIzNCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNOC41OSAxNi4zNGw0LjU4LTQuNTktNC41OC00LjU5TDEwIDUuNzVsNiA2LTYgNnoiLz48L3N2Zz4=")
    no-repeat 50% 50% / 1em 1em;
  width: 1.5em;
  height: 1.5em;
  transition: transform 0.1s linear;
}
summary {
  width: 100%;
  padding: 5px;
  padding-left: 28px;
  text-transform: uppercase;
  font-weight: bold;
  background-color: #413c45;
  /* border-bottom: 1px solid #ccc; */
}
summary:hover {
  color: #a1a1a1;
}
summary:focus {
  outline: none;
}
details[open] summary:before {
  transform: rotate(90deg);
}
details[open] > summary {
  color: #666666;
}
details[open] > summary ~ * {
  animation: open 1s ease;
}
@keyframes open {
  0% {opacity: 0;
  }
  100% {opacity: 1;
  }
}

ul li{
    list-style: decimal;
    margin: 0px 5px 5px 5px;
    border-left: #413c45 dotted 2pt;
    max-width: 250px;
    border-radius: 2%;
    padding : 2px 2px 6px 4px; 
    font-size: 0.8em;
}
.placename,.resname,.hotname{
    color:#413c45;
    font-size: 1.2em;
}
.placedd,.resdd,.hotdd{
    color:#a1a1a1;
    font-size: 1em;
}    
.delli{
    float: right;
    color:#a1a1a1
}
.delli:hover{

  background-color:#fce2d1;

}




/* #sortable { list-style-type: none; margin: 0; padding: 0; width: 60%; }
  #sortable li { margin: 0 5px 5px 5px; padding: 4px; font-size: 1em; height: 1.5em; }
  html>body #sortable li { height: 1.5em; line-height: 1.2em; } */
  .highlight { height: 1.2em; line-height: 1.2em; background-color: #fef0df }
    </style>
</head>
<body>
    <div id="paginator"></div>
    <script src="../../datep/js/jquery.js"></script>
    <script src="../../datep/js/moment.js"></script>
    <script src="../../datep/js/bootstrap-datepicker.js"></script>
    <script src="../../datep/js/bootstrap-datepaginator.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script> 
        $(document).ready(function() {
        $('.datepicker').datepicker({
            format: "yyyy-mm-dd",
    })
    //Listen for the change even on the input
        .change(dateChanged)
        .on('changeDate', dateChanged);
});
    function dateChanged(ev) {
        $(this).datepicker('hide');
        if ($('#startdate').val() != '' && $('#enddate').val() != '') {
            $('#period').text(diffInDays() + ' d.');
        } else {
            $('#period').text("-");
    }
}
    </script>
            <div id="paginator1" class="datepaginator">

<script type="text/javascript">
    var datepaginator = function() {
        return {
            init: function() {
                $("#paginator1").datepaginator()
                // ,
                // $("#paginator4").datepaginator({
                //     onSelectedDateChanged: function(a, t) {
                //     alert("Selected date: " + moment(t).format("Do, MMM YYYY"))
                //     }
                // })
            }
        }
    }();
    $(document).ready(function() {
        datepaginator.init()
    });
    </script>

    <!--  -->
    <div class="container-fluid">
      <div class="row">
        <div class="col-10 offset-1">
            <details>
              <summary>Attractions</summary>
              <body>
                <ul id="sortable">
                  <li class="ui-state-default"><div class='placename'>The Solomon R. Guggenheim Museum</div><div class='delli'><i class="fas fa-times"></i></div><div class='placedd'>Art Museum</div></li>
                  <li class="ui-state-default"><div class='placename'>長長中文字串美術館</div><div class='delli'><i class="fas fa-times"></i></div><div class='placedd'>美術館</div></li>
                  <li class="ui-state-default"><div class='placename'>Museum of Modern Art</div><div class='delli'><i class="fas fa-times"></i></div><div class='placedd'>Art Museum</div></li>
                  <li class="ui-state-default"><div class='placename'>Item 4</div><div class='delli'><i class="fas fa-times"></i></div><div class='placedd'>style</div></li>
                  <li class="ui-state-default"><div class='placename'>Item 5</div><div class='delli'><i class="fas fa-times"></i></div><div class='placedd'>style</div></li>
                  <li class="ui-state-default"><div class='placename'>Item 6</div><div class='delli'><i class="fas fa-times"></i></div><div class='placedd'>style</div></li>
                </ul>      
            </details>
            <details>
              <summary>Food</summary>
              <ul id="sortable">
                <li class="ui-state-default  ui-state-disabled"><div class='resname'>Brunch</div><div class='delli'><i class="fas fa-times"></i></div><div class='resdd'>French Style Restaurant</div></li>
                <li class="ui-state-default  ui-state-disabled"><div class='resname'>長中文字串下午茶時間</div><div class='delli'><i class="fas fa-times"></i></div><div class='resdd'>Cafe</div></li>
                <li class="ui-state-default  ui-state-disabled"><div class='resname'>Supper</div><div class='delli'><i class="fas fa-times"></i></div><div class='resdd'>蔬食餐廳</div></li>
              </ul>
            </details>
            <details>
              <summary>Accomondation</summary>
              <ul id="sortable">
                <li class="ui-state-default  ui-state-disabled"><div class='hotname'>Hotel of the Day</div><div class='delli'><i class="fas fa-times"></i></div><div class='hotdd'></div></li>
              </ul>
            </details>
        </div>
      </div>
    </div>
    <script>
      // Fetch all details element
const details = Array.from(document.querySelectorAll("details"));

// Add onclick listeners
details.forEach(targetDetail => {
targetDetail.addEventListener("click", () => {
  // Close all details that are not targetDetail
  details.forEach(detail => {
    if (detail !== targetDetail) {
      detail.removeAttribute("open");
    }
  });
});
});

  </script>

<script>
  $(function() {
      $("#sortable").sortable({
      placeholder: "highlight"
    });
    $("#sortable").disableSelection();
  } );

  $(document).ready(function(){
    $(".delli").on("click", function(){
     $(this).closest("li").remove(); 
  });
});
  </script>
   <footer>
    <p style="padding-left: 100pt"><input type="submit" value="Bon Voyage"></p>
 </footer>
</body>
</html>

trip/templates/trip/explore.html
{% load static %}
<header>
<div id="myBtnContainer" style="padding-left: 3em">
  <!-- <button class="btn active" onclick="filterSelection('all')"> Show all</button>
  <button class="btn" onclick="filterSelection('Culture')"> Culture </button>
  <button class="btn" onclick="filterSelection('Art')"> Art </button>
  <button class="btn" onclick="filterSelection('Nature')"> Nature </button> -->
  <!-- Willy Code -->
  <button class="btn active WFilterbyName"> Show all </button>
  <button class="btn WFilterbyName">Shopping</button>
  <button class="btn WFilterbyName">Parks</button>
  <!-- <button class="btn WFilterbyName"> Nature </button>
  <button class="btn WFilterbyName">Shopping</button> -->
</div>
</header>
<content>
<div class="row" id='WeStartHere'>



</div>
</content>

trip/templates/trip/left.html
<!-- Tab links -->
{% load static %}
<div class="tab" id="tabContainer">
    <button class="tablinks active" onclick="openDay(event, 'day1')">Day1</button>
    {% for x in triptotalday %}
    <!--
    <button class="tablinks" onclick="openDay(event, 'day2')">Day2</button>
    <button class="tablinks" onclick="openDay(event, 'day3')">Day3</button>
    <button class="tablinks" onclick="openDay(event, 'day4')">Day4</button>
    <button class="tablinks" onclick="openDay(event, 'day5')">Day5</button> -->
    <button class="tablinks" onclick="openDay(event, 'day{{x}}')">day{{x}}</button>
    {% endfor %}
</div>

<!-- Tab content -->
<!-- <div id="day1" class="daytab">

    <button class="accordion">景點</button>
    <div class="panel">
        <ul id="sp1" class="sortable">
            <li class="ui-state-default">
                <div class='delli'>x</div>
            </li>
        </ul>
    </div>
    <span></span>
    <button class="accordion">餐飲</button>
    <div class="panel">
        <ul id="sr1" class="sortable">
        </ul>
    </div>
    <button class="accordion">住宿</button>
    <div class="panel">
        <ul id="sh1">
        </ul>
    </div>
</div>
<div id="day2" class="daytab">
    <button class="accordion">景點</button>
    <div class="panel">
        <ul id="sp2" class="sortable">
        </ul>
    </div>
    <button class="accordion">餐飲</button>
    <div class="panel">
        <ul id="sr2" class="sortable">
        </ul>
    </div>
    <button class="accordion">住宿</button>
    <div class="panel">
        <ul id="sh2">
        </ul>
    </div>
</div>
<div id="day3" class="daytab">
    <button class="accordion">景點</button>
    <div class="panel">
        <ul id="sp3" class="sortable">
        </ul>
    </div>
    <button class="accordion">餐飲</button>
    <div class="panel">
        <ul id="sr3" class="sortable">
        </ul>
    </div>
    <button class="accordion">住宿</button>
    <div class="panel">
        <ul id="sh3">
        </ul>
    </div>
</div>
<div id="day4" class="daytab">
    <button class="accordion">景點</button>
    <div class="panel">
        <ul id="sp4" class="sortable">
        </ul>
    </div>
    <button class="accordion">餐飲</button>
    <div class="panel">
        <ul id="sr4" class="sortable">
        </ul>
    </div>
    <button class="accordion">住宿</button>
    <div class="panel">
        <ul id="sh4">
        </ul>
    </div>
</div>
<div id="day5" class="daytab">
    <button class="accordion">景點</button>
    <div class="panel">
        <ul id="sp5" class="sortable">
        </ul>
    </div>
    <button class="accordion">餐飲</button>
    <div class="panel">
        <ul id="sr5" class="sortable">
        </ul>
    </div>
    <button class="accordion">住宿</button>
    <div class="panel">
        <ul id="sh5">
        </ul>
    </div>
</div> -->



<form method="POST" action="{% url 'trip:trippost' %}" id="leftform">
    {% for item in triptotalpanel %}
    {% csrf_token %}
    <input type="hidden" id="i_daysp{{item}}" name="i_daysp{{item}}" value="">
    <input type="hidden" id="i_daysr{{item}}" name="i_daysr{{item}}" value="">
    <input type="hidden" id="i_daysh{{item}}" name="i_daysh{{item}}" value="">
    <span id="daysp{{item}}" name="daysp{{item}}" style="display: none"></span>
    <span id="daysr{{item}}" name="daysr{{item}}" style="display: none"></span>
    <span id="daysh{{item}}" name="daysh{{item}}" style="display: none"></span>
    <div id="day{{item}}" class="daytab">
        <!-- <div class="panel" style="display: block;">
                <ul id="sp2" class="sortable ui-sortable">
                </ul>
            </div> -->
            <button class="accordion" type="button">ATTRACTION</button>
            <div class="panel" style="display: block;">
                <ul id="sp{{item}}" class="sortable">
                </ul>
            </div>
            <button class="accordion" type="button">RESTAURANT</button>
            <div class="panel" style="display: block;">
                <ul id="sr{{item}}" class="sortable">
                </ul>
            </div>
            <button class="accordion" type="button">ACCOMMODATION</button>
            <div class="panel" style="display: block;">
                <ul id="sh{{item}}">
                </ul>
            </div>
        </div>
        {% endfor %}
    <button type="button" id="send">出發</button>
</form>