member/urls.py
from django.urls import path
from . import views

app_name="member"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('mReg/', views.mReg, name="mReg"),
    path('mainReg/', views.mainReg, name="mainReg"),
    path('Main_index/', views.Main_index, name="Main_index"),
    path('trv_detail/', views.trv_detail, name="trv_detail"),
    path('getStyle/', views.getStyle, name="getStyle"),
]

res/urls.py
from django.urls import path
from . import views

app_name="res"

urlpatterns = [
    path('',views.res),
    #localhost/res/res => booking.html
    path('booking/',views.booking),
    path('lightbox/',views.box)
]

trvl_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('member/', include('member.urls')),
    path('review/',include('review.urls')),
    path('trip/',include('trip.urls')),
    path('res/',include('res.urls')),
    path('hotel/',include('hotel.urls')),
]

member/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Country(models.Model):
    idcountry = models.IntegerField(db_column='idCountry', primary_key=True)  # Field name made lowercase.
    countryname = models.CharField(db_column='Countryname', max_length=45)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'country'


class Member(models.Model):
    idmember = models.IntegerField(db_column='idMember', primary_key=True)  # Field name made lowercase.
    membername = models.CharField(db_column='Membername', max_length=45)  # Field name made lowercase.
    memberemail = models.CharField(db_column='MemberEmail', max_length=45)  # Field name made lowercase.
    memberpassword = models.CharField(db_column='MemberPassword', max_length=45)  # Field name made lowercase.
    memberbday = models.DateField(db_column='MemberBday')  # Field name made lowercase.
    membergender = models.CharField(db_column='MemberGender', max_length=2)  # Field name made lowercase.
    memberidcountry = models.ForeignKey(Country, models.DO_NOTHING, db_column='MemberidCountry')  # Field name made lowercase.
    memberhobby = models.CharField(db_column='MemberHobby', max_length=45, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'member'


class Region(models.Model):
    idregion = models.IntegerField(db_column='idRegion', primary_key=True)  # Field name made lowercase.
    regionname = models.CharField(db_column='Regionname', max_length=45)  # Field name made lowercase.
    idcountry = models.ForeignKey(Country, models.DO_NOTHING, db_column='idCountry')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'region'

member/views.py
from django.shortcuts import render,redirect
from . import member_models as Mbr
import random
from django.http import HttpResponse
import json

# Create your views here.


def index(request):
    request.session.clear()
    isFooterShow = True
    return render(request, 'member/index.html', locals())


def signup(request):
    if request.method == "POST":
        memberid = random.randint(100000, 199999)
        lastname = request.POST["member_lastname"]
        firstname = request.POST["member_firstname"]
        email = request.POST["member_email"]
        pwd = request.POST["member_pwd"]
        birthday = request.POST["member_birthday"]
        # country = request.POST["member_country"]
        country = 9001
        region = request.POST["member_region"]
        gender = request.POST["member_gender"]
        check = request.POST.getlist("member_check")
        checkstr = '/'.join(check)
        sign_data = Mbr.Member()
        sign_data.excute_sql("insert into travel.member (idMember, Membername, MemberEmail, MemberPassword, MemberBday, MemberGender, MemberidCountry, MemberHobby) values(%s, %s, %s, %s, %s, %s, %s, %s)",
                             memberid, (lastname + "/" + firstname), email, pwd, birthday, gender, country, checkstr)
        return redirect('../member/')
        # print(lastname + "/" +firstname+ "/" +email+ "/" +birthday+ "/" +country+ "/" +region+ "/" +gender)
        # print(check)
        # print(type(check))
        # print(checkstr)

    get_city_data = Mbr.Member()
    citylist = get_city_data.select_all("SELECT * FROM travel.country")
    print(citylist)
    isFooterShow = True

    return render(request, 'member/signup.html', locals())


def login(request):
    isLogin = False
    if request.method == "POST":
        email = request.POST["loginmail"]
        pwd = request.POST["loginpwd"]
        # print(email)
        login_chexk = Mbr.Member()
        res = login_chexk.select_one(
            "select idMember from travel.member where MemberEmail = %s and MemberPassword = %s", email, pwd)
        # print(res[0])
        if res is not None and res[0] is not None:
            
            request.session['user'] = res
            request.session.modified = True

            return redirect('../member/Main_index')
        else:
            response = HttpResponse("<script>alert('login fail');location.href='/';</script>")
            return response
        

    return render(request, 'member/Main_index.html', locals())


def Main_index(request):
    isFooterShow = False

    get_city_data = Mbr.Member()
    citylist = get_city_data.select_all("SELECT * FROM travel.country")

    if 'user' in request.session:
        mem_name = Mbr.Member()
        
        memid = request.session['user']
        res = mem_name.select_one(
            "select Membername from travel.member where idMember = %s ", memid)
        useris = res[0].split('/')[1]
        print("GET {}".format(useris))
        isLogin = True
    else:
        print("NO GET")

    return render(request, 'member/Main_index.html', locals())

def trv_detail(request):
    isFooterShow = False

    if 'user' in request.session:
        useris = request.session['user']
        print("GET {}".format(useris))
        isLogin = True
    else:
        print("NO GET")

    return render(request, 'member/trv_detail.html', locals())


def mReg(request):
    if request.method == "GET":
        c_id = request.GET["country"]
        if c_id is not None:
            print("YES")
            get_region_data = Mbr.Member()
            Regionlist = get_region_data.select_all("SELECT * FROM travel.member_region where idCountry = %s",c_id)
            print(json.dumps(Regionlist))
            response = json.dumps({"Reglist" : Regionlist})
            return HttpResponse(response, content_type='application/json')

    return HttpResponse("HI")

def mainReg(request):
    if request.method == "GET":
        c_id = request.GET["country"]
        if c_id is not None:
            print("YES")
            get_region_data = Mbr.Member()
            Regionlist = get_region_data.select_all("SELECT * FROM travel.region where idCountry = %s",c_id)
            print(json.dumps(Regionlist))
            response = json.dumps({"Reglist" : Regionlist})
            return HttpResponse(response, content_type='application/json')

    return HttpResponse("HI")

def getStyle(request):
    if request.method == "GET":
        c_style = request.GET["style"]
        if c_style is not None:
            print("YES")
            get_region_data = Mbr.Member()
            stylelist = None

            if c_style == 'A':
                stylelist = get_region_data.select_all("SELECT distinct(a.type) FROM travel.attraction as a;")
            elif c_style == 'H':
                stylelist = get_region_data.select_all("SELECT distinct(a.type) FROM travel.hotel as a;")
            elif c_style == 'R':
                stylelist = get_region_data.select_all("SELECT distinct(a.type) FROM travel.restaurant as a;")
            else:
                stylelist = get_region_data.select_all("SELECT distinct(a.type) FROM travel.attraction as a;")

            print(json.dumps(stylelist))
            response = json.dumps({"Reglist" : stylelist})
            return HttpResponse(response, content_type='application/json')

    return HttpResponse("HI")

member/templates/member/index.html
{% extends 'master.html' %} {% block main_content %}

<div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light bgimg" style="height: 1000px;">
    <div class="col-md-5 p-lg-5 mx-auto my-5" style="padding-bottom: 0px!important;margin-bottom: 0px!important;">
        <!-- <div class="col-md-12">
            <form style="text-align: left">
                <div class="form-group">
                    <label for="firstname">First Name</label>
                    <input type="text" class="form-control" id="firstname" name="mem_firstname" aria-describedby="firstHelp" placeholder="Enter First Name">
                </div>
                <div class="form-group">
                    <label for="lastname">Last Name</label>
                    <input type="text" class="form-control" id="lastname" name="mem_lastname" aria-describedby="firstHelp" placeholder="Enter Last Name">
                </div>
                <div class="form-group">
                    <label for="email">Email address</label>
                    <input type="email" class="form-control" id="email" name="mem_email" aria-describedby="emailHelp" placeholder="Enter email">
                    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="pwd">Password</label>
                    <input type="password" class="form-control" id="pwd" name="mem_pwd" placeholder="Password">
                </div>
                <div class="form-group">
                    <label for="bday">Birthday</label>
                    <input type="date" class="form-control" id="bday" name="mem_bday">
                </div>

                <div class="form-group">
                    <div class="form-check form-check-inline col-md-5">
                        <input class="form-check-input" type="radio" name="mem_gen" id="gen1" value="M">
                        <label class="form-check-label" for="gen1">Male</label>
                    </div>
                    <div class="form-check form-check-inline col-md-5">
                        <input class="form-check-input" type="radio" name="mem_gen" id="gen2" value="F">
                        <label class="form-check-label" for="gen2">Female</label>
                    </div>
                </div>

                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label" for="exampleCheck1">Check me out</label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div> -->
        <h1 class="display-4 font-weight-normal" style="font-weight: bolder;color:white;margin-top: 130px;"><i class="fab fa-telegram-plane" style="margin-right: 40px;"></i>D O C U M E N T</h1>
        <a class="btn btn-outline-secondary" href="{% url 'member:signup' %}" style="margin-top: 30px;">Sign up</a>
        <p class="lead font-weight-normal"style="font-weight: bolder;color:white;margin-top: 60px;">Customize your travel itinerary with the smartest trip planner</p>
        
    </div>
    <!-- <div class="product-device box-shadow d-none d-md-block"></div>
  <div class="product-device product-device-2 box-shadow d-none d-md-block"></div> -->
</div>

{% endblock %}

member/templates/member/signup.html
{% extends 'master.html' %} {% load static%} {% block style_part %}
<link rel="stylesheet" href="{% static 'styles/signup.css' %}"> {% endblock %} {% block main_content %}

<div class="position-relative">
        <h1 style="background-image: url({% static 'images/sititimg.jpg' %}); text-align: center;padding: 20px;color: white;">建立您的會員資料</h1>
    <div class="col-md-5 mx-auto" style="padding-bottom: 0px!important;margin-bottom: 0px!important;margin-top: 20px;">
        <!-- <hr class="myhr">  -->

        <form action="{% url 'member:signup' %}" method="POST">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-6">
                    <label class="sr-only required" for="member_lastname">姓氏</label>
                    <input type="text" class="form-control" id="member_lastname" name="member_lastname" placeholder="姓氏" required="required">
                </div>
                <div class="form-group col-md-6">
                    <label class="sr-only required" for="member_firstname">名字</label>
                    <input type="text" class="form-control" id="member_firstname" name="member_firstname" placeholder="名字" required="required">
                </div>
            </div>
            <div class="form-group">
                <label class="sr-only required" for="member_email">電子信箱</label>
                <input type="email" class="form-control" id="member_email" name="member_email" placeholder="電子信箱" required="required">
            </div>
            <div class="form-group">
                <label class="sr-only required" for="member_pwd">密碼</label>
                <input type="password" class="form-control" id="member_pwd" name="member_pwd" placeholder="請輸入您的密碼">
            </div>
            <div class="form-group">
                <label class="sr-only required" for="member_birthday">生日</label>
                <input type="text" class="form-control" id="member_birthday" name="member_birthday" placeholder="請輸入您的生日,例如：1990-03-30">
            </div>
            

            <hr class="myhr">

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="member_country">居住國家</label>
                    <select id="member_country" name="member_country" class="dlist form-control">
                        <option selected>Choose...</option>
                        {% for c_item in citylist %}
                        <option value={{c_item.0}}>{{c_item.1}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group col-md-6">
                    <label for="member_region">居住區域</label>
                    <select id="member_region" name="member_region" class="form-control">
                        <option selected>Choose...</option>
                        <option value="cv">...</option>
                    </select>
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-6">
                    <input class="" type="radio" name="member_gender" id="gen1" value="M">
                    <label class="" for="gen1">男</label>
                </div>
                <div class="form-group col-md-6">
                    <input class="" type="radio" name="member_gender" id="gen2" value="Ｆ">
                    <label class="" for="gen1">女</label>
                </div>
            </div>

            <hr class="myhr">

            <div class="form-group">
                <fieldset>
                    <legend>請告知我們您的旅遊喜好</legend>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-3 form-control" style="border: none;">
                                <input class="" type="checkbox" id="gridCheck1" name="member_check" value="nv">
                                <label class="form-check-label" for="gridCheck">自然景觀</label>
                            </div>
                            <div class="col-md-3 form-control" style="border: none;">
                                <input class="" type="checkbox" id="gridCheck2" name="member_check" value="cl">
                                <label class="form-check-label" for="gridCheck">文化知性</label>
                            </div>
                            <div class="col-md-3 form-control" style="border: none;">
                                <input class="" type="checkbox" id="gridCheck3" name="member_check" value="sp">
                                <label class="form-check-label" for="gridCheck">購物時尚</label>
                            </div>
                            <div class="col-md-3 form-control" style="border: none;">
                                <input class="" type="checkbox" id="gridCheck4" name="member_check" value="ch">
                                <label class="form-check-label" for="gridCheck">休閒親子</label>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>

            <hr class="myhr">

            <div class="container" style="text-align: center;">
                <div class="">
                    <input type="submit" class="col-md-2 btn btn-outline-secondary form-control" value="註冊">
                </div>
            </div>
        </form>


    </div>
    <!-- <div class="product-device box-shadow d-none d-md-block"></div>
  <div class="product-device product-device-2 box-shadow d-none d-md-block"></div> -->
</div>

{% endblock %}

{% block script_part %} 
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<script>
    $().ready(function(){
        $('.dlist').change(function(){
        var a = $( ".dlist option:selected" ).val();
        // console.log(a);
        get_region(a);
        
        });

        function get_region(id){
            $.get("{% url 'member:mReg' %}",{'country': id},
            function(data){
                // console.log(data);
                console.log(data.Reglist[0][0]);
                console.log(data.Reglist.length)
                // console.log(typeof(data));
                // var list = $.parseJSON(data);
                // console.log(list);

                var reg_sel = $('#member_region');

                reg_sel.empty()

                var reg_sel_flg = $(document.createDocumentFragment());

                for(i =0; i < data.Reglist.length; i++){
                    console.log(data.Reglist[i][0]);
                    var opt = $('<option></option>');
                    opt.text(data.Reglist[i][1])
                    opt.val(data.Reglist[i][0])

                    reg_sel_flg.append(opt)
                }

                reg_sel.append(reg_sel_flg)

            });
        };
    });
    
</script>
{% endblock %}

member/templates/member/test.html
{% extends 'master.html' %}
{% block slide_content %}

<h1>hi</h1>

{% endblock %}

member/templates/member/trv_detail.html
{% extends 'master.html' %} {% load static%} {% block style_part %} {% endblock %} {% block main_content %}
<div class="position-relative">
    <h1 style="background-image: url({% static 'images/titimg2.jpg' %}); text-align: center;padding: 20px;color: white; background-repeat: no-repeat;
    background-attachment: fixed;background-position: center;background-size: cover;">行程資訊</h1>
    <div class="col-md-5 mx-auto" style="padding-bottom: 0px!important;margin-bottom: 0px!important;margin-top: 20px;">
        <!-- <hr class="myhr">  -->

        <div class="container">
            <nav>
                <div class="nav nav-tabs" id="nav-tab" role="tablist">
                    <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home"
                        aria-selected="true">Home</a>
                    <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile"
                        aria-selected="false">Profile</a>
                    <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact"
                        aria-selected="false">Contact</a>
                </div>
            </nav>
            <div class="tab-content" id="nav-tabContent">
                <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                          <h4 class="panel-title">
                            <a data-toggle="collapse" href="#collapse1">Collapsible list group</a>
                          </h4>
                        </div>
                        <div id="collapse1" class="panel-collapse collapse">
                          <ul class="list-group">
                            <li class="list-group-item">One</li>
                            <li class="list-group-item">Two</li>
                            <li class="list-group-item">Three</li>
                          </ul>
                          <div class="panel-footer">Footer</div>
                        </div>
                      </div>
                </div>
                <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                    Nulla est ullamco ut irure incididunt nulla Lorem Lorem minim irure officia enim reprehenderit. Magna duis labore cillum sint adipisicing exercitation ipsum. Nostrud ut anim non exercitation velit laboris fugiat cupidatat. Commodo esse dolore fugiat sint velit ullamco magna consequat voluptate minim amet aliquip ipsum aute laboris nisi. Labore labore veniam irure irure ipsum pariatur mollit magna in cupidatat dolore magna irure esse tempor ad mollit. Dolore commodo nulla minim amet ipsum officia consectetur amet ullamco voluptate nisi commodo ea sit eu.
                </div>
                <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                    Sint sit mollit irure quis est nostrud cillum consequat Lorem esse do quis dolor esse fugiat sunt do. Eu ex commodo veniam Lorem aliquip laborum occaecat qui Lorem esse mollit dolore anim cupidatat. Deserunt officia id Lorem nostrud aute id commodo elit eiusmod enim irure amet eiusmod qui reprehenderit nostrud tempor. Fugiat ipsum excepteur in aliqua non et quis aliquip ad irure in labore cillum elit enim. Consequat aliquip incididunt ipsum et minim laborum laborum laborum et cillum labore. Deserunt adipisicing cillum id nulla minim nostrud labore eiusmod et amet. Laboris consequat consequat commodo non ut non aliquip reprehenderit nulla anim occaecat. Sunt sit ullamco reprehenderit irure ea ullamco Lorem aute nostrud magna.
                </div>
            </div>
        </div>


    </div>
</div>
<!-- <div class="container">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home"
                aria-selected="true">Home</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile"
                aria-selected="false">Profile</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact"
                aria-selected="false">Contact</a>
        </div>
    </nav>
    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
            Et et consectetur ipsum labore excepteur est proident excepteur ad velit occaecat qui minim occaecat veniam. Fugiat veniam incididunt anim aliqua enim pariatur veniam sunt est aute sit dolor anim. Velit non irure adipisicing aliqua ullamco irure incididunt irure non esse consectetur nostrud minim non minim occaecat. Amet duis do nisi duis veniam non est eiusmod tempor incididunt tempor dolor ipsum in qui sit. Exercitation mollit sit culpa nisi culpa non adipisicing reprehenderit do dolore. Duis reprehenderit occaecat anim ullamco ad duis occaecat ex.
        </div>
        <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
            Nulla est ullamco ut irure incididunt nulla Lorem Lorem minim irure officia enim reprehenderit. Magna duis labore cillum sint adipisicing exercitation ipsum. Nostrud ut anim non exercitation velit laboris fugiat cupidatat. Commodo esse dolore fugiat sint velit ullamco magna consequat voluptate minim amet aliquip ipsum aute laboris nisi. Labore labore veniam irure irure ipsum pariatur mollit magna in cupidatat dolore magna irure esse tempor ad mollit. Dolore commodo nulla minim amet ipsum officia consectetur amet ullamco voluptate nisi commodo ea sit eu.
        </div>
        <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
            Sint sit mollit irure quis est nostrud cillum consequat Lorem esse do quis dolor esse fugiat sunt do. Eu ex commodo veniam Lorem aliquip laborum occaecat qui Lorem esse mollit dolore anim cupidatat. Deserunt officia id Lorem nostrud aute id commodo elit eiusmod enim irure amet eiusmod qui reprehenderit nostrud tempor. Fugiat ipsum excepteur in aliqua non et quis aliquip ad irure in labore cillum elit enim. Consequat aliquip incididunt ipsum et minim laborum laborum laborum et cillum labore. Deserunt adipisicing cillum id nulla minim nostrud labore eiusmod et amet. Laboris consequat consequat commodo non ut non aliquip reprehenderit nulla anim occaecat. Sunt sit ullamco reprehenderit irure ea ullamco Lorem aute nostrud magna.
        </div>
    </div>
</div> -->
{% endblock %} {% block script_part %} {% endblock %}