member/urls.py
from django.urls import path
from . import views

app_name="member"
urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('mReg/', views.mReg, name="mReg"),
    path('mainReg/', views.mainReg, name="mainReg"),
    path('Main_index/', views.Main_index, name="Main_index"),
    path('trv_detail/', views.trv_detail, name="trv_detail"),
    path('getStyle/', views.getStyle, name="getStyle"),
]

res/urls.py
from django.urls import path
from . import views

app_name="res"

urlpatterns = [
    path('',views.res),
    #localhost/res/res => booking.html
    path('booking/',views.booking),
    path('lightbox/',views.box)
]

trvl_proj/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('member.urls')),
    path('member/', include('member.urls')),
    path('review/',include('review.urls')),
    path('trip/',include('trip.urls')),
    path('res/',include('res.urls')),
    path('hotel/',include('hotel.urls')),
]

templates/footer.html
<footer class="container py-5">
    <div class="row foostyle">
        <div class="col-6 col-md">
            <h5>Features</h5>
            <ul class="list-unstyled text-small">
                <li>
                    <a class="text-muted" href="#">Website feature</a>
                </li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>How to use</h5>
            <ul class="list-unstyled text-small">
                <li>
                    <a class="text-muted" href="#">FAQ</a>
                </li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>How we work</h5>
            <ul class="list-unstyled text-small">
                <li>
                    <a class="text-muted" href="#">analysis</a>
                </li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>About</h5>
            <ul class="list-unstyled text-small">
                <li>
                    <a class="text-muted" href="#">Team</a>
                </li>
            </ul>
        </div>
        
    </div>
    <hr>
    <div class="col-12 col-md foostyle">
        <!-- <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg> -->
        <!-- <small class="d-block mb-3 text-muted">&copy; 2018. yiki</small> -->
        &copy; 2018. yiki
    </div>
</footer>

templates/master.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://www.w3.org/2000/svg">

    <title>Document</title>

    <!-- Bootstrap core CSS -->
    <link href="http://bootstrap.hexschool.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="{% static 'styles/product.css' %}">
    <link rel="stylesheet" href="{% static 'styles/master.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Noto" rel="stylesheet">

    <style>
		#row-main {
			overflow-x: hidden; /* necessary to hide collapsed sidebar */
		}
		#mycontent {
			transition: 0.3s ease;
		}

		#sidebar {
			transition: 0.3s ease;
		}
		.cus_collapsed {
			display: none; /* hide it for small displays */
		}
		/* @media (min-width: 992px) {
			.collapsed {
				display: block;
				margin-left: -25%; 
			}
        } */

        

        .titlelink:hover {             
            padding-bottom: 7px;
            text-decoration: none;
            border-bottom: 3px solid #00a699;
        }

        #exampleInputPassword1::placeholder {
            color: white;
        }

        #exampleInputEmail1::placeholder {
            color: white;
        }

        .cusbtn {
            background-color: #00a699;
            border-radius: 12px;
            border: white 2px solid;
            color: white;
            /* width: 100%; */
            padding: 8px 60px;
            text-align: center;
            font-size: 16px;
            font-weight: 500;
            margin: 4px 2px;
            transition: 0.3s;
            display: inline-block;
            text-decoration: none;
            cursor: pointer;
            /* margin-top: 20px; */
        }

        .cusbtn:hover {
            color: white
        }

        *{
            /* font-family: 'Roboto', sans-serif; */
            font-family: 'Noto Sans TC', sans-serif;
        }

        



    </style>

    {% block style_part %} {% endblock %}
</head>

<body>
    <span style="display: none" name="lalala" id="lalala">A</span>
    {% include 'navbar.html' %}

    <!-- <div class="row row-main">
        <div id="sidebar" class="col-md-3 collapsed">

            <h1>HI</h1>
        </div>
        <div id="mycontent" class="col-md-12">
        </div>
    </div> -->

    {% block main_content %} {% endblock %}


    {% if isFooterShow  == True%}
    <div class="row">
        {% include 'footer.html' %}
    </div>
    {% else %}
        
    {% endif %}
    





    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="http://bootstrap.hexschool.com/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="http://bootstrap.hexschool.com/assets/js/vendor/popper.min.js"></script>
    <script src="http://bootstrap.hexschool.com/dist/js/bootstrap.min.js"></script>
    <script src="http://bootstrap.hexschool.com/assets/js/vendor/holder.min.js"></script>
    <!-- <script src="{%static 'scripts/review.js'%}"> -->

    </script>
    <script>
        Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
        });
    </script>

    {% block script_part %} {% endblock %}

    <script>
        $(document).ready(function () {
            // $(".toggle-sidebar").click(function () {
            //     $("#sidebar").toggleClass("collapsed");
            //     $("#mycontent").toggleClass("col-md-12 col-md-9");
            //     return false;
            // });

            $('#login_a').click(function(){
                $('#login_from').toggleClass("cus_collapsed",5000);
                $('#login_a').toggleClass("cus_collapsed");
            })


            $('#at').click(function(){
                $('#lalala').text('A');
                $('#myBtnContainer').empty();
                get_region('A')
            })
            $('#ht').click(function(){
                $('#lalala').text('H');
                $('#myBtnContainer').empty();
                get_region('H')
            })
            $('#rt').click(function(){
                $('#lalala').text('R');
                $('#myBtnContainer').empty();
                get_region('R')
            })
            // {% url 'member:getStyle' %}
            function get_region(style){
            $.get("{% url 'member:getStyle' %}",{'style': style},
            function(data){
                // /member/getStyle
                // console.log(data);
                // console.log(data.Reglist[0][0]);
                // console.log(data.Reglist.length)
                // console.log(typeof(data));
                // var list = $.parseJSON(data);
                // console.log(list);

                var reg_sel = $('#myBtnContainer');

                reg_sel.empty()

                var reg_sel_flg = $(document.createDocumentFragment());

                //  <button class="btn active WFilterbyName"> Show all</button>
                //  <button class="btn WFilterbyName"> Culture </button>
                //  <button class="btn WFilterbyName"> Art </button>
                //  <button class="btn WFilterbyName"> Nature </button>
                //  <button class="btn WFilterbyName"> 小吃 </button>
                var showall = $('<button class="btn active WFilterbyName">Show all</button>');
                reg_sel_flg.append(showall)
                for(i =0; i < data.Reglist.length; i++){
                    console.log(typeof(data.Reglist[i][0]));
                    str_t = "'" + data.Reglist[i][0] + "'"
                    strbtn = '<button class="btn WFilterbyName" onclick="BTNclick('+ str_t +')"></button>'
                    var opt = $(strbtn);
                    opt.text(data.Reglist[i][0])
                    // opt.val(data.Reglist[i][0])

                    reg_sel_flg.append(opt)
                }

                reg_sel.append(reg_sel_flg)

            });
        };



        });
    </script>
</body>

</html>

templates/navbar.html
<!-- <nav class="site-header sticky-top py-1">
    <div class="container d-flex flex-column flex-md-row justify-content-between" style="max-width: 100%;">
         <div class="col-md-4" style="text-align: left">
            <a class="py-2 d-none d-md-inline-block toggle-sidebar" href="#">manage</a>
        </div>
        <div class="col-md-4" style="text-align: center">
            <a class="navbar-brand py-2 d-none d-md-inline-block" href="#">Document</a>
        </div>
        <div class="col-md-4" style="text-align: right">
            <a class="py-2 d-none d-md-inline-block" href="#">H!, Yuki</a>
        </div> 
        <a class="py-2" href="#">Document</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Location</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Hotel</a>
        <a class="py-2 d-none d-md-inline-block" href="#">Restaurant</a>
    </div>
</nav> -->
<nav class="navbar navbar-expand-lg site-header sticky-top">
    <a style="padding-left: 2em "class="navbar-brand" href="#"> <i class="fab fa-telegram-plane" style="margin-right: 20px;"></i> D O C U M E N T</a>
    <button class="navbar-toggler" type="button" style="border: 1px solid silver;" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <!-- <span class="navbar-toggler-icon"></span> -->
        <i class="fas fa-bars" style="color: silver;"></i>  
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding: 1.5em 1.5em 0.8em 1.5em; text-transform: uppercase">
        <ul class="navbar-nav mr-auto">
            {% if isLogin  == True%}
                
            <li class="nav-item">
                <a class="nav-link titlelink" href="#" id="at">Attraction</a>
            </li>
            <li class="nav-item">
                <a class="nav-link titlelink" href="#" id="ht">Hotel</a>
            </li>
            <li class="nav-item">
                <a class="nav-link titlelink" href="#" id="rt">Restaurant</a>
            </li>

            {% endif %}
        </ul>
        <!-- form-inline my-2 my-lg-0 -->
        {% if isLogin  == True%}
        <a class="nav-link" href="#" id="login_a">LOGOUT</a>
        {% else %}
        <a class="nav-link" href="#" id="login_a">LOGIN</a>
        {% endif %}
        
        <div class="cus_collapsed" id="login_from">
            
            <div class="container">
                <div class="row">
                    <form class="" style="display: block;color:silver;" action="{% url 'member:login' %}" method="POST">
                        {% csrf_token %}
                        <div style="float: left;">
                            <div class="input-group col-auto" style="width: 50%;float: left;">
                                <!-- <label for="exampleInputEmail1">Email address</label> style="display: inline-block;"-->
                                <div class="input-group-prepend">
                                    <div class="input-group-text" style="background-color: black;border: none;"><i class="fas fa-envelope" style="color: white;"></i></div>
                                  </div>
                                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" name="loginmail" style="background-color: silver;
                                border:none;border-bottom-color: gray;">
                                <!-- <i class="fas fa-envelope" style=" float: left; position: relative;z-index: 2; margin-right: 6px;margin-top: -20px;"></i> -->
                            </div>
                            <div class="input-group col-auto" style="width: 50%;float: right;">
                                <!-- <label for="exampleInputPassword1">Password</label> style="display: inline-block;"-->
                                <div class="input-group-prepend">
                                    <div class="input-group-text" style="background-color: black;border:none;"><i class="fas fa-lock" style="color: white;"></i></div>
                                  </div>
                                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password" name="loginpwd" style="background-color: silver;border:none ;border-bottom:2px solid silver;">
                            </div>
                        </div>
                        <div style="float: right;">
                            <div class="col-auto" style="">
                                <button type="submit" class="btn btn-outline-secondary">LOGIN</button>
                            </div>
                        </div>
                        
                        
                        <!-- <div class="col-md-5" style="display: inline-block;" display: inline-block;>
                            <input type="checkbox" class="" id="exampleCheck1">
                            <label class="" for="exampleCheck1">Check me out</label>
                        </div>
                        <div class="col-md-5" style="display: inline-block;">
                            <a href="">forget password?</a>
                        </div> -->






                    </form>
                </div>
            </div>

        </div>
    </div>
</nav>

templates/tripmenu.html
<div class="pos-f-t">
                    
    <nav class="navbar navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
    <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">
              <h4 class="text-white">Collapsed content</h4>
              <span class="text-muted">Toggleable via the navbar brand.</span>
            </div>
          </div>
  </div>